version: '3'
services:
  db:
    restart: always
    image: mysql:latest
    env_file: ./.env
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

  adminer:
    restart: always
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

  minds:
    restart: always
    image: mindsdb/mindsdb:v24.3.5.0-arm64
    ports:
      - 47334:47334
    depends_on:
      - db
